# Generated by Django 2.1.3 on 2018-11-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181124_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=999, null=True),
        ),
    ]
