# Generated by Django 2.1.3 on 2018-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20181128_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='booked_seat',
            field=models.TextField(blank=True, max_length=999, null=True),
        ),
    ]
