# Generated by Django 2.1.3 on 2018-11-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20181130_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booker',
            new_name='TicketBooker',
        ),
    ]
