# Generated by Django 2.1.3 on 2018-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20181202_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooker',
            name='tel',
            field=models.CharField(default='', max_length=15),
        ),
    ]
