# Generated by Django 2.1.3 on 2018-11-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(auto_now=True),
        ),
    ]
