# Generated by Django 2.1.3 on 2018-11-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20181129_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='seats',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
