# Generated by Django 2.1.3 on 2018-11-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20181130_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='theater',
            field=models.CharField(max_length=10),
        ),
    ]
