# Generated by Django 2.1.3 on 2018-11-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20181130_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='booked_seat',
        ),
    ]
