# Generated by Django 2.1.3 on 2018-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_ticketbooker_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooker',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
