# Generated by Django 2.1.3 on 2018-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_ticketbooker_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketbooker',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
