# Generated by Django 2.1.3 on 2018-12-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_ticketbooker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooker',
            name='seat',
            field=models.CharField(max_length=255),
        ),
    ]
